### ISSUE TITLE
初回リリース

### ISSUE THREAD

**Issue by ayaka-kitabora** [ayaka-kitabora/nicca-scheduler-ios#19]
https://developer.apple.com/jp/app-store/product-page/
*  アカウント作成 (やっておく)
*  画像・説明文作成 (やっておく)
*  xcodeでstoreにupする
*  審査に出す

**Comment by Pocchi** [comment]
- [x] アカウント作成 https://developer.apple.com/jp/programs/ => pending
- [x] プライバシーポリシーページ https://sparkly-father-3a9.notion.site/1fd49b8ac34246cc83f1498e69127428
- [x] アプリアイコン https://github.com/ayaka-kitabora/nicca-scheduler-ios/pull/21
- [x] 画面スクショ https://help.apple.com/app-store-connect/?lang=ja-jp#/devd274dd925
- [x] App名 `日課スケジューラー`
- [x] サブタイトル `タスクを日ごとにスケジュール`
- [x] 説明文  `シンプルなタスクスケジューラー。テキストを毎日少しずつ進める人におすすめ。1日何ページ行うかチェックリストを作成します。`
- [x] プロモーション用テキスト170文字  `個人で初めて作成したアプリです。まだ機能も少ないですが、よろしくお願いいたします。`

**Comment by ayaka-kitabora** [comment]
2021/10/13公開済み
https://apps.apple.com/jp/app/%E6%97%A5%E8%AA%B2%E3%82%B9%E3%82%B1%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%A9%E3%83%BC/id1589960177
